steps:
  # Build & push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-west2-docker.pkg.dev/$PROJECT_ID/my-repo/fullstack-app:$SHORT_SHA',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-west2-docker.pkg.dev/$PROJECT_ID/my-repo/fullstack-app:$SHORT_SHA'
      ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'fullstack-service',
        '--image', 'us-west2-docker.pkg.dev/$PROJECT_ID/my-repo/fullstack-app:$SHORT_SHA',
        '--region', 'us-west2',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-west2-docker.pkg.dev/$PROJECT_ID/my-repo/fullstack-app:$SHORT_SHA'
