options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - '-t'
  - '$REGION-docker.pkg.dev/$PROJECT_ID/backend-repo/server:$SHORT_SHA'
  - './server'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - '$REGION-docker.pkg.dev/$PROJECT_ID/backend-repo/server:$SHORT_SHA'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - '-t'
  - '$REGION-docker.pkg.dev/$PROJECT_ID/frontend-repo/client:$SHORT_SHA'
  - './client'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - '$REGION-docker.pkg.dev/$PROJECT_ID/frontend-repo/client:$SHORT_SHA'
images:
- '$REGION-docker.pkg.dev/$PROJECT_ID/backend-repo/server:$SHORT_SHA'
- '$REGION-docker.pkg.dev/$PROJECT_ID/frontend-repo/client:$SHORT_SHA'